@startuml 車両貸出システム
class 空車リスト {
- 車番号:int
- 空車: String
- 日時:String
}
class 車 {
- 車番号:String
- 車種:String
- 貸出料金:int
- 駆動方式:String
- 状態空車、予約済み、貸出中等:String
}
class 顧客 {
- 顧客ID:String
- 顧客名:String
- 電話番号:String
- 郵便番号:String
- 住所:String
+ setName(顧客名:String):void
}
class 予約 {
- 予約番号:int
- 車番号
- 顧客ID:String
- 予約日時:String
}
class 貸出 {
-貸出番号
-貸出日時:String
-車番号
-返却日時:String
+ 貸出():void
}
@enduml