@startuml コンビニ弁当
|客|
|客|
|店員|
|店員|


|客|
start
    : 弁当をレジに持っていく;
|店員|
fork
|客|
    : お金を支払う;
|店員|
    : 精算する;
fork again
    if (温めますか?)then(No)
    else (Yes)
        :弁当を温める;
endif

: 弁当を袋に入れる;

end fork
|客|
: 弁当を手に持つ;
stop
@enduml