@startuml ユースケース図
left to right direction
actor 利用者 #DDDDDD;line:black;line.bold;
actor ホテル従業員 #DDDDDD;line:black;line.bold;
actor 管理者 #DDDDDD;line:black;line.bold;
rectangle ホテル宿泊予約システム {
usecase ログインする
usecase 会員登録をする
usecase キャンペーン価格で予約する
usecase (<u>予約</u>\n拡張点\nキャンペーン中か判断する) as input
usecase 空室状況を閲覧する   
usecase 空室状況を入力する
usecase 予約の集計をする
}
input <. (キャンペーン価格で予約する) : <<extend>>
利用者 ---> キャンペーン価格で予約する
利用者 -> 会員登録をする
利用者 --> 空室状況を閲覧する
ログインする ..>予約の集計をする: <<include>>
ログインする ..> input : << include >>
会員登録をする <. ログインする : <<include>>
予約の集計をする <-- 管理者
空室状況を入力する <-- ホテル従業員
ログインする .right.>空室状況を入力する: <<include>>
@enduml