@startuml
object 注文{
    合計
}
object 注文詳細{
    数量
    小計
}
object 割引クーポン{
値引額
期限
}
object 商品{
    名称
    単価
}
object ドリンク{
    種別
}
object カップ{
    サイズ
}
object フード{
}
object レシピ{
}
object 材料 {
}
object ハンバーガー{
    種別
}
object ポテト{
    サイズ
}
object パン{
}
object 肉{
}
object 野菜{
}
object チーズ{
}
パン -up-|>材料
肉 -up-|>材料
野菜 -up-|>材料
チーズ -up-|>材料
材料 "1..*"-right-"1..*"ハンバーガー
ハンバーガー -up-|>レシピ
ポテト-up-|>レシピ
レシピ "1"-right-"1" フード
レシピ -up-|>商品
カップ "1..3"-right-"0..*"ドリンク
ドリンク -right-|>商品
商品 "1"-up-"0..*"注文詳細
注文詳細 "0..*"-right-"0..1"割引クーポン
注文 "1..*" o-right- 注文詳細
@enduml